#!/usr/bin/env python3
"""Assemble a drop-in distribution folder that mirrors the RoF2 client layout, so a user
can copy its whole contents into their client dir and every file lands where it belongs.

Produces (default ./dist):
  dist/
    rof2ClientPlus.asi            -> <RoF2>/                 (the mod DLL)
    eq-window-fix                 -> <RoF2>/                 (optional Linux windowed-mode helper)
    rcp*.s3d  (29 archives)       -> <RoF2>/                 (classic model archives)
    Resources/GlobalLoad.txt      -> <RoF2>/Resources/       (manifest, stock + the mod's lines)
    uifiles/rcp/**                -> <RoF2>/uifiles/rcp/      (options UI, fonts, target-rings)
    INSTALL.txt                                              (how to copy it in)

So `cp -r dist/* /path/to/RoF2/` (Linux) or xcopy (Windows) is a complete install.

The 29 .s3d are resolved in this order: regenerate from --src-dir sources (authoritative,
verified) if present; else use a complete --build-dir; else a prebuilt --fallback-s3d dir.
Resources/GlobalLoad.txt is generated by applying the mod's patch to the vendored stock
manifest (tools/GlobalLoad.stock.txt) -- byte-reproducing the known-good in-game file.

Pure stdlib. Usage:
  build_dist.py [--out dist] [--build-dir build] [--src-dir DIR] [--fallback-s3d DIR]
                [--asi build/rof2ClientPlus.asi] [--uifiles uifiles/rcp]
                [--eq-window-fix build/eq-window-fix] [--stock tools/GlobalLoad.stock.txt]
"""
import os, sys, shutil, subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from build_models import RECIPE  # the 29 output names + the recipe
from patch_globalload import load as gl_load, patch as gl_patch, save as gl_save, is_patched
from patch_moddat import load as md_load, save as md_save, is_patched as md_is_patched, block_lines as md_block

S3D_NAMES = [r[0] + ".s3d" for r in RECIPE]

INSTALL_TXT = """\
rof2ClientPlus - drop-in install
================================

Copy the ENTIRE contents of this folder into your RoF2 client directory (the folder
that contains eqgame.exe), merging and overwriting when asked:

  Linux:    cp -r ./* /path/to/RoF2/
  Windows:  xcopy /E /Y * C:\\path\\to\\RoF2\\

What lands where:
  rof2ClientPlus.asi         -> <RoF2>/                 the mod (Miles loads every *.asi on launch)
  rcp*.s3d  (29 files)       -> <RoF2>/                 classic model archives (model-swap feature)
  Resources/GlobalLoad.txt   -> <RoF2>/Resources/       tells the client to load the rcp archives
  Resources/moddat.ini       -> <RoF2>/Resources/       first-person camera offsets for the swap models
  uifiles/default/*.xml      -> <RoF2>/uifiles/default/  option-window overrides incl. the /rcpoptions
                                                         window; load under ANY skin (see NOTE below)
  uifiles/rcp/               -> <RoF2>/uifiles/rcp/      mod fonts + target-ring graphics (not a skin)
  eq-window-fix              -> <RoF2>/                 OPTIONAL, Linux/Wine windowed-mode helper only

Requirements:
  * Sound must be enabled (Sound=TRUE in eqclient.ini) -- that is how the .asi gets loaded.
  * Relaunch the client after copying.
  * In game: /rcp lists commands; /rcpoptions opens the options window.

NOTE - uifiles/default/ (the /rcpoptions window):
  These go into the DEFAULT skin so the mod UI loads no matter which skin you run -- you can
  install and select your own custom UI skin on top.
    * EQUI_RcpOptions.xml  = the mod's options window (a new standalone skin file).
    * EQUI.xml             = stock + ONE <Include> line that loads EQUI_RcpOptions.xml.
    * EQUI_OptionsWindow.xml / EQUI_AdvancedDisplayOptionsWnd.xml = widened copies of stock
                             (clipped option text fixed).
  Copying OVERWRITES three stock files (EQUI.xml + the two option windows). `make install`
  saves the pristine originals once as *.rcpbak; a plain copy does not, so back them up first
  if you want them. A custom skin that ships its OWN EQUI.xml would need this one <Include>
  line added to it to load /rcpoptions.

IMPORTANT - Resources/GlobalLoad.txt:
  This is the STANDARD RoF2 manifest with the mod's lines added; for a normal client it is
  safe to overwrite. If YOU have a customized GlobalLoad.txt (e.g. other model mods), do NOT
  overwrite it. Instead, from the rof2ClientPlus source tree run:
      python3 tools/patch_globalload.py --file <RoF2>/Resources/GlobalLoad.txt
  (idempotent; it only adds the rcp lines and backs up your file first).

Uninstall: delete rof2ClientPlus.asi, the rcp*.s3d, and uifiles/rcp/ from the client dir,
and restore Resources/GlobalLoad.txt (its stock form is Resources/GlobalLoad.txt.rcpbak, or
run patch_globalload.py --revert).
"""


def have_all(d, names):
    return bool(d) and os.path.isdir(d) and all(os.path.isfile(os.path.join(d, n)) for n in names)


def sources_present(src_dir):
    if not src_dir or not os.path.isdir(src_dir):
        return False
    need = {r[1] for r in RECIPE}  # source basenames
    return all(os.path.isfile(os.path.join(src_dir, s)) for s in need)


def resolve_s3d(build_dir, src_dir, fallback):
    """Return (dir_with_all_29, how) or exit."""
    if sources_present(src_dir):
        print(f">> regenerating 29 .s3d from sources ({src_dir}) into {build_dir}")
        r = subprocess.run([sys.executable, os.path.join(HERE, "build_models.py"),
                            "--src-dir", src_dir, "--out-dir", build_dir])
        if r.returncode == 0 and have_all(build_dir, S3D_NAMES):
            return build_dir, "regenerated from source (verified)"
        print("   (regen incomplete; falling back to prebuilt)")
    if have_all(build_dir, S3D_NAMES):
        return build_dir, f"prebuilt in {build_dir}"
    if have_all(fallback, S3D_NAMES):
        return fallback, f"prebuilt backup ({fallback})"
    missing = [n for n in S3D_NAMES if not (have_all(build_dir, [n]) or have_all(fallback or "", [n]))]
    raise SystemExit(f"ERROR: cannot find or build the 29 .s3d. Provide --src-dir (build inputs) "
                     f"or --fallback-s3d (prebuilt). Missing e.g.: {missing[:3]}")


def copy_tree_files(src, dst, exts):
    """Copy files with given extensions from src (recursively) into dst, preserving structure."""
    n = 0
    for root, _dirs, files in os.walk(src):
        rel = os.path.relpath(root, src)
        for f in files:
            if exts and not f.lower().endswith(exts):
                continue
            outdir = os.path.join(dst, rel) if rel != "." else dst
            os.makedirs(outdir, exist_ok=True)
            shutil.copyfile(os.path.join(root, f), os.path.join(outdir, f))
            n += 1
    return n


def main():
    a = sys.argv[1:]
    def opt(name, default):
        return a[a.index(name) + 1] if name in a else default
    out = opt("--out", os.path.join(REPO, "dist"))
    build_dir = opt("--build-dir", os.path.join(REPO, "build"))
    src_dir = opt("--src-dir", "/home/joshua/Games/RoF2-modelswap-backup/model-inputs")
    fallback = opt("--fallback-s3d", "/home/joshua/Games/RoF2-modelswap-backup/built-s3d")
    asi = opt("--asi", os.path.join(build_dir, "rof2ClientPlus.asi"))
    uifiles = opt("--uifiles", os.path.join(REPO, "uifiles"))
    eqwf = opt("--eq-window-fix", os.path.join(build_dir, "eq-window-fix"))
    stock = opt("--stock", os.path.join(HERE, "GlobalLoad.stock.txt"))

    if not os.path.isfile(asi):
        raise SystemExit(f"ERROR: {asi} not found -- run `make` first.")

    # fresh staging dir
    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(out)

    # 1. the mod DLL
    shutil.copyfile(asi, os.path.join(out, "rof2ClientPlus.asi"))
    # 2. optional windowed-mode helper
    if os.path.isfile(eqwf):
        shutil.copyfile(eqwf, os.path.join(out, "eq-window-fix"))
    # 3. uifiles tree, preserving structure: default/*.xml (option-window overrides that
    #    load under every skin) + rcp/{fonts,targetrings} (mod assets loaded by path).
    ui_n = copy_tree_files(uifiles, os.path.join(out, "uifiles"),
                           (".xml", ".spritefont", ".tga"))
    # 4. the 29 model archives
    s3d_dir, how = resolve_s3d(build_dir, src_dir, fallback)
    for n in S3D_NAMES:
        shutil.copyfile(os.path.join(s3d_dir, n), os.path.join(out, n))
    # 5. Resources/GlobalLoad.txt = stock + the mod's patch (reproduces the in-game file)
    lines, eol, tnl = gl_load(stock)
    if not is_patched(lines):
        lines = gl_patch(lines)
    os.makedirs(os.path.join(out, "Resources"), exist_ok=True)
    gl_save(os.path.join(out, "Resources", "GlobalLoad.txt"), lines, eol, tnl)
    # 5b. Resources/moddat.ini = stock + the alias-model camera offsets (model-swap)
    md_stock = os.path.join(HERE, "moddat.stock.ini")
    ml, meol, mtnl = md_load(md_stock)
    if not md_is_patched(ml):
        ml = ml + md_block()
    md_save(os.path.join(out, "Resources", "moddat.ini"), ml, meol, mtnl)
    # 6. install notes
    with open(os.path.join(out, "INSTALL.txt"), "w") as f:
        f.write(INSTALL_TXT)

    total = sum(os.path.getsize(os.path.join(r, f)) for r, _d, fs in os.walk(out) for f in fs)
    print(f">> dist assembled at {out}")
    print(f"   .asi + {'eq-window-fix + ' if os.path.isfile(os.path.join(out,'eq-window-fix')) else ''}"
          f"{len(S3D_NAMES)} .s3d ({how}) + {ui_n} uifiles + Resources/GlobalLoad.txt + Resources/moddat.ini + INSTALL.txt")
    print(f"   total {total/1e6:.1f} MB. Install: copy the contents of {out}/ into <RoF2>/")


if __name__ == "__main__":
    main()
