// rof2ClientPlus - Zeal-style spell book window (/rcpbook, alias /rcpsb).
//
// A native SIDL window replacing the stock paged spell book: one searchable,
// sortable, multi-column list of spells (icon / name / level / mana / cast /
// recast / duration / target / category / subcategory), a "Show unscribed"
// checkbox (dimmed rows for spells your class can use but has not scribed),
// and a spell-description pane. Clicking a spell's icon cell picks the spell
// up on the cursor exactly like the stock book does - drop it on a spell gem
// to memorize (the client's native memorize flow runs from there).
//
// The window's SIDL template ships as the standalone uifiles/default/
// EQUI_RcpSpellBook.xml (generated by tools/gen_rcp_spellbook_ui.py), included
// from the skin's EQUI.xml like EQUI_RcpOptions.xml; it is instantiated lazily
// via CreateXWndFromTemplate and driven entirely by the per-frame poll.
//
// When the "[SpellBook] NewWindow" setting is ON (the "New spell book window"
// checkbox on the /rcpoptions Display tab, or /rcpbook on), every path that
// opens the stock spell book (keybind, book button, /book) is redirected: the
// per-frame poll hides the stock window the moment it appears and toggles this
// one instead - EXCEPT while a memorize/scribe is running, when the client
// itself needs the stock book open for the animation.
#pragma once

class RcpService;

class SpellBookUI {
 public:
  explicit SpellBookUI(RcpService *rcp);

  // Called every frame from the main loop (dllmain ProcessGameEvents hook).
  void on_frame();

  // Release all cached window/control handles + per-UI caches (window rebuilds
  // lazily on the next open). Wired to the LoadSidl EQUI.xml-reload detour in
  // rcp_options_ui.cpp and to the not-in-game gate, same as RcpOptionsUI.
  void drop_handles();
};

// Accessors for the options-window UI / commands to read+write the settings.
namespace spellbook_settings {
bool get_enabled();              // true = the new window replaces the stock spell book.
void set_enabled(bool on);       // Applies next frame + persists to ini.
bool get_show_unscribed();       // true = unscribed class spells are listed (dimmed).
void set_show_unscribed(bool on);
}  // namespace spellbook_settings

// Right-click-to-scribe (/rcpscribe): right-click a spell scroll in a bag to
// scribe it into the first free spell book slot. Opens whichever spell book is
// active (this window when enabled, else the stock book); standing up or
// closing the book cancels the scribe exactly like the stock flow.
namespace spellbook_scribe {
bool get_enabled();
void set_enabled(bool on);
// Called from equip_item.cpp's CInvSlot::HandleRButtonUp detour (the single
// owner of that hook) with the clicked item and its ItemGlobalIndex fields.
// Returns true when the click was consumed (a scribe was started or refused
// with a chat message); false lets equip/native right-click handling run.
bool handle_inventory_rclick(void *item, int location, const short slots[3]);
}  // namespace spellbook_scribe
